
@api = http://localhost:3000/api/v1/board

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "Quantity": 17,
    "Description": "It's old"
}

###
GET {{api}}/1002

###
DELETE {{api}}/1003

###
GET {{api}}/count

###
PUT {{api}}/1002
Content-Type: application/json

{
    "Quantity": 134,
    "Description": "OLD TIME",
    "Status": "Sucess"
}